"""fix_sqlmodel_relationship_mappings

Revision ID: 28aa9d3accd5
Revises: 7f05d47aacd0
Create Date: 2026-05-24 14:35:22.005547+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



revision: str = '28aa9d3accd5'
down_revision: Union[str, None] = '7f05d47aacd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
