"""add soft delete columns

Revision ID: 7f05d47aacd0
Revises: 0c6a5ae74969
Create Date: 2026-05-24 10:54:53.630470+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "7f05d47aacd0"
down_revision: Union[str, None] = "0c6a5ae74969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_sessions",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "interview_sessions", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_interview_sessions_is_deleted"),
        "interview_sessions",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "messages",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column("messages", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_messages_is_deleted"), "messages", ["is_deleted"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_is_deleted"), table_name="messages")
    op.drop_column("messages", "deleted_at")
    op.drop_column("messages", "is_deleted")
    op.drop_index(
        op.f("ix_interview_sessions_is_deleted"), table_name="interview_sessions"
    )
    op.drop_column("interview_sessions", "deleted_at")
    op.drop_column("interview_sessions", "is_deleted")
    # ### end Alembic commands ###
